### PR TITLE
Pass-through the EBC port for docking.

### PR DESCRIPTION
**Pull request by lucasb-eyer**
DEFAULT TO NONE, ONLY ONE ROBOT HAS A LIGHT IN THERE.
Feels good to shout once in the morning.

See strands-project/scitos_apps#120

### CODE REVIEW

**Comment by marc-hanheide** [comment]
but this is a hack, right? We don't want this, but we want to fix https://github.com/strands-project/scitos_apps/pull/120!

**Comment by marc-hanheide** [comment]
I would suggest not to change it here, but in https://github.com/strands-project/scitos_apps/tree/hydro-devel/scitos_docking/launch. Doing it in here, just confuses people even more. Only people that **HAVE** a light should set it here.

**Comment by lucasb-eyer** [comment]
The problem is, I think, that people are not supposed to write their own full launchfiles but rather include `strands_navigation.launch` and friends and set parameters. Otherwise there is no reason for `strands_*.launch` to exist, is there?

**Comment by marc-hanheide** [comment]
yes, you're right. So this is indeed helping others as well. So, I agree, this is a useful addition, but not the correct solution to the problem in https://github.com/strands-project/scitos_apps/pull/120

But yes, happy to have this in!

**Pull request merged**
