### PR TITLE
Ability to include site-specific movebase parameters.

### PR DESCRIPTION
**Pull request by lucasb-eyer**
Goes together with strands-project/strands_movebase#18

### CODE REVIEW

**Comment by nilsbore** [comment]
This looks OK to me, better to do it this way than to have to clone strands_movebase every time. But might I suggest to just load those parameters after also loading the default ones? That way you can just choose which parameters to swap out? The parameter server loads them sequentially and picks the last ones so that would work.

**Comment by lucasb-eyer** [comment]
Huh, I thought that I did exactly that?

**Comment by lucasb-eyer** [comment]
Yeah, look at the other PR, it's the very last param file that's loaded (in movebase) and I even added the comment saying exactly that in ALLCAPS ;-)

**Comment by nilsbore** [comment]
Aah, my mistake, didn't see that you didn't have the conditional tag for the other arguments. Looks good!

**Pull request merged**
