### PR TITLE
using door pass launch

### PR DESCRIPTION
**Pull request by bfalacerda**
needs https://github.com/strands-project/strands_apps/pull/42

### CODE REVIEW

**Comment by marc-hanheide** [comment]
we won't use it at AAF but I assume it doesn't hurt to have it in?

**Comment by bfalacerda** [comment]
yeah, these nodes are quiet when their action servers are not called

**Comment by bfalacerda** [comment]
this has been on bob for some days now, so merging along with https://github.com/strands-project/strands_apps/pull/42

**Comment by bfalacerda** [comment]
or not, I'm not allowed

**Pull request merged**
